### ISSUE TITLE
Optional types do not get type casted by dtyper

### ISSUE THREAD

**Issue by NodeJSmith** [rec/dtyper#7] opened 2023-07-28 21:36 UTC
I am trying to use `dtyper` with a package that has a command with optional parameters, in this case it is `Optional[List[str]]`. When called from the command line this is converted to an empty list, but when using `dtyper` it is returned as None, which is causing the command to fail.

The actual conversion happens in [click](https://github.com/pallets/click/blob/f45198a3bcaf41d72d31273f9e6a2e3dfeccd19b/src/click/core.py#L2355)'s `Parameter.process_value` call.

The package I'm fiddling with is [dbx](https://github.com/databrickslabs/dbx), if you install that then the below is a reproducible example. I will try to find one that is simpler, as I believe dbx requires configuration files and potentially authentication to get to the point of failure and I don't know `typer` or `click` well enough to make my own example.

```python
import dtyper
from dbx.commands.deploy import deploy


def dbx_deploy():
    catalog: str = sys.argv[1]
    workflow_name = f"{PACKAGE_NAME}_({catalog})"

    file_path = os.path.join(os.getcwd(), f"{catalog}_deployment.yaml")

    _deploy = dtyper.function(deploy)
    _deploy(workflow_name=workflow_name, deployment_file=file_path)
```

**Comment by rec** [comment] 2023-07-29 13:28
I couldn't get the test script to run, my attempts (with fixes after each phase) below.

Do you get the same behavior with `typer`?  `dtyper` is a thin wrapper over `typer`, it's not clear how it would introduce any new behavior like that that `typer` didn't have before.

```
(fix) tom@bolt:/code/dtyper$ python test_dbx.py 
Traceback (most recent call last):
  File "test_dbx.py", line 15, in <module>
    dbx_deploy()
  File "test_dbx.py", line 6, in dbx_deploy
    catalog: str = sys.argv[1]
NameError: name 'sys' is not defined
(fix) tom@bolt:/code/dtyper$ python test_dbx.py 
Traceback (most recent call last):
  File "test_dbx.py", line 16, in <module>
    dbx_deploy()
  File "test_dbx.py", line 7, in dbx_deploy
    catalog: str = sys.argv[1]
IndexError: list index out of range
(fix) tom@bolt:/code/dtyper$ python test_dbx.py test
Traceback (most recent call last):
  File "test_dbx.py", line 16, in <module>
    dbx_deploy()
  File "test_dbx.py", line 8, in dbx_deploy
    workflow_name = f"{PACKAGE_NAME}_({catalog})"
NameError: name 'PACKAGE_NAME' is not defined
(fix) tom@bolt:/code/dtyper$ python test_dbx.py test
Traceback (most recent call last):
  File "test_dbx.py", line 16, in <module>
    dbx_deploy()
  File "test_dbx.py", line 13, in dbx_deploy
    _deploy(workflow_name=workflow_name, deployment_file=file_path)
  File "/Users/tom/synthetic/code/dtyper/dtyper.py", line 284, in wrapped
    return typer_command(*bound.args, **bound.kwargs)
  File "/Users/tom/synthetic/code/dtyper/.direnv/python-3.7/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tom/synthetic/code/dtyper/.direnv/python-3.7/lib/python3.7/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/tom/synthetic/code/dtyper/.direnv/python-3.7/lib/python3.7/site-packages/click/core.py", line 939, in make_context
    self, info_name=info_name, parent=parent, **extra  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'workflow_name'
(fix) tom@bolt:/code/dtyper$ 
```

**Comment by rec** [comment] 2023-07-31 08:12
Well, let me know if you can get me more information, and I'll look into it!

I'm fairly sure that the issue is in fact `dtyper`, but programming is hard. :-) 

Let me know how I can help, but I'm going to close this for right now so it isn't hanging over my head. :-D

**Closed by rec** 2023-07-31 08:12 UTC
